c_stdlib_version:          # [osx and x86_64]
- '10.14'                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
- '10.14'                  # [osx and x86_64]

cgo_compiler:
- go-cgo
cgo_compiler_version:
- '1.23'
