{% set go_min = ">=1.22" %}
{% set version = "0.32.1" %}

{% set name = "kubo" %}
{% set gomodule = "github.com/ipfs/" ~ name %}
{% set go_min = ">=1.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: src/{{ gomodule }}
    url: https://{{ gomodule }}/releases/download/v{{ version }}/{{ name }}-source.tar.gz
    sha256: ffbda89ac0d9dbe9ee3c79195ed477312b315a27310b462716629c1c5db60bed

build:
  number: 0

requirements:
  build:
    - {{ compiler("go-cgo") }}  # [build_platform == target_platform]
    - go {{ go_min }}           # [build_platform != target_platform]
    - go-cgo {{ go_min }}       # [build_platform != target_platform]
    - posix                     # [win]
    - make                      # [unix]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - go-licenses
  host:
    - openssl
  run_constrained:
    - go-ipfs >=9000

{% set cid = "/ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z" %}
{% set ipfs_args = "--debug" %}

test:
  commands:
    - ipfs --version
    - ipfs --help
    - ipfs commands
    - ipfs {{ ipfs_args }} init
    - echo "hello conda-forge" > hello.txt
    - ipfs {{ ipfs_args }} add hello.txt

about:
  home: https://ipfs.tech
  license: Apache-2.0 or MIT
  license_file:
    # directly provided by upstream
    - src/{{ gomodule }}/LICENSE-APACHE
    - src/{{ gomodule }}/LICENSE-MIT
    - library_licenses/

  summary: IPFS implementation in Go

  description: |
    Kubo (go-ipfs) the earliest and most widely used implementation of IPFS.

    It includes:
      - an IPFS daemon server
      - extensive command line tooling
      - an HTTP Gateway (/ipfs/, /ipns/) for serving content to HTTP browsers
      - an HTTP RPC API (/api/v0) for controlling the daemon node

  doc_url: https://docs.ipfs.tech
  dev_url: https://{{ gomodule }}

extra:
  recipe-maintainers:
    - bollwyvl
