# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.40.0"
  name: kubo
  go_mod: github.com/ipfs/kubo
  go_cmd: cmd/ipfs
  go_build: go build -v -buildmode=pie -trimpath -modcacherw
  go_bin: ${{ "%LIBRARY_BIN%\\ipfs.exe" if win else "$PREFIX/bin/ipfs" }}
  go_mod_fuse: bazil.org/fuse
  license_ignore: |-
    ${{ go_mod }}
    ${{ go_mod_fuse }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://${{ go_mod }}/releases/download/v${{ version }}/${{ name }}-source.tar.gz
    sha256: 6ef776c9b974c6406b4b68e877c3f535144679289ac40d988f58cc58c822d277
    target_directory: github.com/ipfs/kubo
  # manually-recovered licenses
  - url: https://raw.githubusercontent.com/bazil/fuse/refs/heads/master/LICENSE
    target_directory: library_licenses_manual/${{ go_mod_fuse }}
    sha256: b0310b2546ffbf6433751c452c66e5548460e49d1a4fc8260ba3ba93c81b18d7

build:
  number: 0
  script:
    content:
      - ${{ "export" if unix else "set" }} "GOPATH=${{ SRC_DIR }}"
      - cd ${{ go_mod }}
      - go-licenses save ${{ go_cmd }} --save_path "${{ SRC_DIR }}/library_licenses" {% for i in license_ignore | split %}--ignore ${{ i }} {% endfor %}
      - ${{ go_build }} ${{ go_cmd }} -o "${{ go_bin }}"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - make
  run_constraints:
    - go-ipfs >=9000

tests:
  - script:
      - ipfs --version
      - ipfs --help
      - ipfs commands
      - ipfs --debug init
      - echo "hello conda-forge" > hello.txt
      - ipfs --debug add hello.txt

about:
  license: Apache-2.0 OR MIT
  license_file:
    # directly provided by upstream
    - ${{ go_mod }}/LICENSE-APACHE
    - ${{ go_mod }}/LICENSE-MIT
    - library_licenses/
    - library_licenses_manual/
  summary: IPFS implementation in Go
  description: |
    Kubo (go-ipfs) the earliest and most widely used implementation of IPFS.

    It includes:
    - an IPFS daemon server
    - extensive command line tooling
    - an HTTP Gateway (/ipfs/, /ipns/) for serving content to HTTP browsers
    - an HTTP RPC API (/api/v0) for controlling the daemon node

  homepage: https://ipfs.tech
  repository: https://${{ go_mod }}
  documentation: https://docs.ipfs.tech

extra:
  recipe-maintainers:
    - bollwyvl
