# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.38.1"
  name: kubo
  cid: /ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/ipfs/kubo/releases/download/v${{ version }}/${{ name }}-source.tar.gz
    sha256: 3ccb8e17b839b679b8ac8e6336402fd2f3da511e27e4a049220bc16dad03c43f
    target_directory: src/github.com/ipfs/kubo

build:
  number: 0
  script:
    file: build-kubo

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("go-cgo") }}
    - ${{ stdlib("c") }}
    - go-licenses
    - make
  host:
    - openssl
  run_constraints:
    - go-ipfs >=9000

tests:
  - script:
      - ipfs --version
      - ipfs --help
      - ipfs commands
      - ipfs --debug init
      - echo "hello conda-forge" > hello.txt
      - ipfs --debug add hello.txt

about:
  license: Apache-2.0 OR MIT
  license_file:
    # directly provided by upstream
    - src/github.com/ipfs/kubo/LICENSE-APACHE
    - src/github.com/ipfs/kubo/LICENSE-MIT
    - library_licenses/
  summary: IPFS implementation in Go
  description: |
    Kubo (go-ipfs) the earliest and most widely used implementation of IPFS.

    It includes:
    - an IPFS daemon server
    - extensive command line tooling
    - an HTTP Gateway (/ipfs/, /ipns/) for serving content to HTTP browsers
    - an HTTP RPC API (/api/v0) for controlling the daemon node

  homepage: https://ipfs.tech
  repository: https://github.com/ipfs/kubo
  documentation: https://docs.ipfs.tech

extra:
  recipe-maintainers:
    - bollwyvl
